language: node_js

node_js:
  - 14
  - 12
  - 10

install:
  - npm install

script:
  - npm run test

after_success:
  - npm run coveralls

notifications:
  email: false

services:
  - docker

branches:
  only:
    - master
    - develop
